--Show all customers.
SELECT * FROM customers;

--Show all products costing more than ₱5,000.
SELECT * FROM products WHERE price > 5000;

--Show all orders with a status of Delivered.
SELECT * FROM orders WHERE order_status = 'Delivered';

--Count the total number of orders.
SELECT COUNT(*) AS total_number_of_orders FROM orders;

--Find the average product price.
SELECT AVG(price) AS average_price FROM products;

--Find the total revenue from the orders table.
SELECT SUM(total_amount) AS total_sales FROM orders;

--List products sorted by price from highest to lowest.
SELECT * FROM products ORDER BY price DESC;

--Which customer placed each order?
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    o.order_id,
    o.order_date,
    o.order_status,
    o.total_amount
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id;

--Show customer name and their order, order_status and amount
SELECT
  CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    o.order_id,
    o.order_status,
    o.total_amount
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id;

--Show every product included in every order.
SELECT
    o.order_id,
    o.order_date,
    o.order_status,
    p.product_name,
    oi.quantity,
    oi.unit_price
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id;

--Show all customers, including those who have never placed an order.
SELECT 
	c.first_name || ' ' || c.last_name  AS customer_name,
	o.order_id,
	o.order_status
FROM customers c
LEFT JOIN orders o
ON c.customer_id  = o.customer_id;

--How much has each customer spent?
SELECT
    c.first_name || ' ' || c.last_name AS customer_name,
    COALESCE(SUM(o.total_amount), 0) AS total_spent
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY total_spent DESC
LIMIT 3;

--Show the total revenue generated by each product.
SELECT p.product_name, 
	  COALESCE(SUM(oi.quantity * oi.unit_price),0) AS  total_revenue
FROM products p
LEFT JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY total_revenue DESC;

--Which products sold the highest number of units?
SELECT p.product_name,
	  COALESCE(SUM(oi.quantity),0) AS units_sold
FROM products p
LEFT JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY units_sold DESC;
	   
--Show customers who have never placed an order.
SELECT c.first_name || ' ' || c.last_name AS customer_name 
FROM customers c 
LEFT JOIN orders o
ON c.customer_id = o.customer_id
WHERE o.customer_id IS NULL;

--On average, how much does each customer spend per order
SELECT 
	ROUND(AVG(total_amount),2) AS average_order_value 
FROM orders
WHERE order_status IN ('Delivered', 'Shipped');

--How many orders did each customer place?
SELECT
    c.first_name || ' ' || c.last_name AS customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY total_orders DESC;

--How many different products has each customer purchased?
SELECT
    c.first_name || ' ' || c.last_name AS customer_name,
    COUNT(DISTINCT oi.product_id) AS unique_products
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
LEFT JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY unique_products DESC;

--Show customers who have placed more than one order.
SELECT
    c.first_name || ' ' || c.last_name AS customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
 HAVING COUNT(o.order_id) > 1
ORDER BY total_orders DESC;



