--Show all customers.
SELECT * FROM customers;

--Show all products costing more than ₱5,000.
SELECT * FROM products WHERE price > 5000;

--Show all orders with a status of Delivered.
SELECT * FROM orders WHERE order_status = 'Delivered';

--Count the total number of orders.
SELECT COUNT(*) AS total_number_of_orders FROM orders;

--Find the average product price.
SELECT AVG(price) AS average_price FROM products;

--Find the total revenue from the orders table.
SELECT SUM(total_amount) AS total_sales FROM orders;

--List products sorted by price from highest to lowest.
SELECT * FROM products ORDER BY price DESC;

--Which customer placed each order?
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    o.order_id,
    o.order_date,
    o.order_status,
    o.total_amount
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id;

--Show customer name and their order, order_status and amount
SELECT
  CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    o.order_id,
    o.order_status,
    o.total_amount
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id;

--Show every product included in every order.
SELECT
    o.order_id,
    o.order_date,
    o.order_status,
    p.product_name,
    oi.quantity,
    oi.unit_price
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id;

--Show all customers, including those who have never placed an order.
SELECT 
	c.first_name || ' ' || c.last_name  AS customer_name,
	o.order_id,
	o.order_status
FROM customers c
LEFT JOIN orders o
ON c.customer_id  = o.customer_id;

--How much has each customer spent?
SELECT
    c.first_name || ' ' || c.last_name AS customer_name,
    COALESCE(SUM(o.total_amount), 0) AS total_spent
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY total_spent DESC
LIMIT 3;

--Show the total revenue generated by each product.
SELECT p.product_name, 
	  COALESCE(SUM(oi.quantity * oi.unit_price),0) AS  total_revenue
FROM products p
LEFT JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY total_revenue DESC;

--Which products sold the highest number of units?
SELECT p.product_name,
	  COALESCE(SUM(oi.quantity),0) AS units_sold
FROM products p
LEFT JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY units_sold DESC;
	   
--Show customers who have never placed an order.
SELECT c.first_name || ' ' || c.last_name AS customer_name 
FROM customers c 
LEFT JOIN orders o
ON c.customer_id = o.customer_id
WHERE o.customer_id IS NULL;

--On average, how much does each customer spend per order
SELECT 
	ROUND(AVG(total_amount),2) AS average_order_value 
FROM orders
WHERE order_status IN ('Delivered', 'Shipped');

--How many orders did each customer place?
SELECT
    c.first_name || ' ' || c.last_name AS customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY total_orders DESC;

--How many different products has each customer purchased?
SELECT
    c.first_name || ' ' || c.last_name AS customer_name,
    COUNT(DISTINCT oi.product_id) AS unique_products
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
LEFT JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY unique_products DESC;

--Show customers who have placed more than one order.
SELECT
    c.first_name || ' ' || c.last_name AS customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
 HAVING COUNT(o.order_id) > 1
ORDER BY total_orders DESC;

--Classify every product based on its price.
SELECT
	product_name, price,
	CASE
	    WHEN price >= 20000 THEN 'Premium'
	    WHEN price >= 10000 THEN 'Mid-range'
	    ELSE 'Budget'
	END AS  price_category
FROM products
ORDER BY price DESC;

--Classify customers based on their total spending.
SELECT 
	c.first_name || ' ' || c.last_name AS customer_name,
	COALESCE(SUM(o.total_amount),0) AS total_spent,
	CASE
	    WHEN COALESCE(SUM(o.total_amount), 0) >= 50000 THEN 'VIP'
	    WHEN COALESCE(SUM(o.total_amount), 0) >= 10000 THEN 'Regular'
	    ELSE 'New'
	END AS customer_type
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, customer_name
ORDER BY total_spent DESC;

--Check Orders Table Schema
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'orders';
--Show all orders placed today.
 SELECT * FROM orders WHERE DATE(order_date) = CURRENT_DATE; 
--CAST(order_date AS DATE)
SELECT * FROM orders WHERE order_date::DATE = CURRENT_DATE; 

--How many orders were placed in each month?
SELECT
	EXTRACT(MONTH FROM order_date) AS month,
	COUNT(order_id) AS total_orders
FROM orders
GROUP BY month
ORDER BY month ASC;

--How much revenue did we generate each month?
SELECT
    DATE_TRUNC('month', order_date) AS month,
    SUM(total_amount) AS total_revenue
FROM orders
WHERE order_status IN ('Delivered', 'Shipped')
GROUP BY month
ORDER BY month;

--Which day of the week receives the most orders?
SELECT 
	EXTRACT(DOW FROM order_date) AS day_of_week,
	COUNT(order_id) AS total_orders
FROM orders
GROUP BY day_of_week
ORDER BY total_orders DESC;


--Which day of the week receives the most orders? with (CASE)
SELECT 
	CASE 
		WHEN EXTRACT(DOW FROM order_date) = 1 THEN 'Monday'
		WHEN EXTRACT(DOW FROM order_date) = 2 THEN 'Tuesday'
		WHEN EXTRACT(DOW FROM order_date) = 3 THEN 'Wednesday'
		WHEN EXTRACT(DOW FROM order_date) = 4 THEN 'Thursday'
		WHEN EXTRACT(DOW FROM order_date) = 5 THEN 'Friday'
		WHEN EXTRACT(DOW FROM order_date) = 6 THEN 'Saturday'
		ELSE 'Sunday'
	END AS day_of_week,
	COUNT(order_id) AS total_orders
FROM orders
GROUP BY day_of_week
ORDER BY total_orders DESC;


--Which day of the week receives the most orders? with (TRIM AND TO_CHAR)
SELECT
    TRIM(TO_CHAR(order_date, 'Day')) AS day_name,
    COUNT(*) AS total_orders
FROM orders
GROUP BY day_name
ORDER BY total_orders DESC;


--Which day of the week receives the orders? with (CASE AND GROUP BY DAY OF WEEK)
SELECT
    CASE
        WHEN EXTRACT(DOW FROM order_date) = 1 THEN 1
        WHEN EXTRACT(DOW FROM order_date) = 2 THEN 2
        WHEN EXTRACT(DOW FROM order_date) = 3 THEN 3
        WHEN EXTRACT(DOW FROM order_date) = 4 THEN 4
        WHEN EXTRACT(DOW FROM order_date) = 5 THEN 5
        WHEN EXTRACT(DOW FROM order_date) = 6 THEN 6
        ELSE 7
    END AS day_order,
    CASE
        WHEN EXTRACT(DOW FROM order_date) = 1 THEN 'Monday'
        WHEN EXTRACT(DOW FROM order_date) = 2 THEN 'Tuesday'
        WHEN EXTRACT(DOW FROM order_date) = 3 THEN 'Wednesday'
        WHEN EXTRACT(DOW FROM order_date) = 4 THEN 'Thursday'
        WHEN EXTRACT(DOW FROM order_date) = 5 THEN 'Friday'
        WHEN EXTRACT(DOW FROM order_date) = 6 THEN 'Saturday'
        ELSE 'Sunday'
    END AS day_name,
    COUNT(*) AS total_orders
FROM orders
GROUP BY day_order, day_name
ORDER BY day_order;


--Orders from the last 30 days:
SELECT *
FROM orders
WHERE order_date >= NOW() - INTERVAL '30 days';

--Orders placed yesterday:
SELECT *
FROM orders
WHERE DATE(order_date) = CURRENT_DATE - INTERVAL '1 day';


--Expected delivery date (7 days after ordering):
SELECT
    order_id,
    order_date,
    order_date + INTERVAL '7 days' AS expected_delivery
FROM orders;

--Show orders from the last 30 days.
SELECT 
	order_id, customer_id, order_date FROM orders
	WHERE order_date >= NOW() - INTERVAL '30 days';

--Show orders from the last 30 calendar days.
SELECT 
	order_id, customer_id, order_date FROM orders
	WHERE order_date >= CURRENT_DATE - INTERVAL '30 days';

--How many days have passed since the order was placed relative to today.
SELECT
    order_id,
    order_date,
    CURRENT_DATE - DATE(order_date) AS days_since_order
FROM orders;







